### ISSUE TITLE
Support uncertainties and distrib information in reports

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#133]
We already support the creation of models with distrib information. See
https://sbmlutils.readthedocs.io/en/stable/notebooks/sbml_distrib.html

The complete specification of information is provided here:
[sbml-level-3-distrib-package-proposal.pdf](https://github.com/matthiaskoenig/sbmlutils/files/6017397/sbml-level-3-distrib-package-proposal.pdf)

The main things to support are:
-  uncertainties, with their information being available in the info node dictionary of sbase https://github.com/matthiaskoenig/sbmlutils/blob/bb27e0049c9af9e5f0abe82304daace20dec9c00/src/sbmlutils/report/sbmlreport.py#L294. I.e. there should be an `info["uncertainties"]` which stores uncertainty information. Uncertainties are also SBases so you have to have the full information on them.

Example files can be found in the repository.
In addition to the uncertainties there is also additional MathML symbols in there. This will most likely break the reports (but will be fixed as part of #208.

- [x] read uncertainty information and store in SBase info dict
- [x] display uncertainty information in HTML report. This requires to add information on all objects if there are uncertainties in there.
- [x] add testcases for the example distrib models which can be seen in https://sbmlutils.readthedocs.io/en/stable/notebooks/sbml_distrib.html and are part of the code

This is good medium size issue which shows you how to understand what additional information exists in the packages, how to add it to the info dictionaries and how to render it.

**Comment by matthiaskoenig** [comment]
@sankha555 This is a great issue which will give you a next level of understanding.

**Comment by sankha555** [comment]
@matthiaskoenig Sure, I will start studying these resources and start working on the issue. Thanks a lot!

**Comment by matthiaskoenig** [comment]
@sankha555 
I just refactored the SBMLReport and split it into a clean `sbmlinfo.py` which manages the collection of the information via a class and the `formating.py` which handles formating related things.

See
https://github.com/matthiaskoenig/sbmlutils/commit/5015c507b758a39e09e3a93ef5f24d1084ab2877

Please update to this latest changes which will make it much easier for you to add the uncertainty information.

**Comment by sankha555** [comment]
@matthiaskoenig this new modularity looks really great! I have pulled the latest changes and went through the refactoring. I would start working on branches based on this update now. Thanks!

**Comment by sankha555** [comment]
@matthiaskoenig I have tried to go through the resources above and have formed some idea about the issue. I will try to come up with a patch to add the uncertainities information to the model by adding to the newly created Info class. Also, I suppose that I have to add the tags in the HTML report template to support displaying the uncertainities dict information, just like the other components like species, compartments, rules, parameters, etc. I hope this should implement the 2nd point in the requirements above. I suppose that the implementation for the other components in the reports would give me a good idea as to how to implement the issue for the uncertainities too. 

Work has been a bit tardy today and yesterday due to some exams, I am very sorry for that. I will try to implement the ideas into the codebase and come up with the patch this week. I thought of giving an update here, please let me know if you have any additional inputs for me and kindly pardon me for the slacked workflow over the last two days. I will try to complete the issue properly as soon as possible this week. 

Thanks & Regards
Sankha Das

**Comment by matthiaskoenig** [comment]
Yes, you need to add the uncertainties on the `info_sbase`. The uncertainties are themself SBases so you have to add all the information there. I suggest to do in a first step the update of the `info_sbase` and I would review the code. In a second step we make a plan for rendering the HTML. But don't do both things at once. 
Start with getting the info in the `context` for rendering and add the test models with uncertainties and distrib information to the tests.
No worries, take your time. You are already doing very much.

**Comment by sankha555** [comment]
Sure, I would follow these milestones for the workflow and proceed accordingly with the issue. Thanks a lot Sir!

**Comment by matthiaskoenig** [comment]
@sankha555 First part is merged.

Now you should add some HTML snippet for the uncertainties in the report. Just do a first draft of the rendering then we have to do an iteration on it. But for now it would be good that you try this on your own.

**Comment by sankha555** [comment]
Sure Sir, I would give it a good attempt on my own and try to come up with a patch for the rendering. I would take some ideas from the implementation of the other objects and hope to complete it for the uncertainties. Thanks!
