### ISSUE TITLE
Support OMEX/COMBINE archives for SBML reports

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#225]
- [ ] Read SBML models provided in COMBINE archives and write the reports for all SBML files in the COMBINE archive.

**Comment by sankha555** [comment]
@matthiaskoenig Sorry that I could not start working on the issue yesterday as I had committed in the mail, due to some issues here at my end. I will extract the models to read and generate reports for them. I just wanted to confirm if this source is good for extracting the models or I should go to some other source:

[https://github.com/SED-ML/sedml-test-suite](https://github.com/SED-ML/sedml-test-suite)

Please let me know if I should get the models from some other source. I would make tests and generate the reports for them and make a pull request to add the same. Thanks!

**Comment by matthiaskoenig** [comment]
We would add our own test models. For now you should have a look at the publication describing the archive
https://pubmed.ncbi.nlm.nih.gov/25494900/
There is nothing more to do here for now. I will add the necessary example for reading a combine archive so you can work from there on. This will depend on https://github.com/matthiaskoenig/sbmlutils/issues/227

**Comment by sankha555** [comment]
Sure Sir, I would make the changes as soon as the models are up, and will continue with the study of this publication now. Thanks!
