### ISSUE TITLE
Make report view handling more robust for breaking changes

### ISSUE THREAD

**Issue by sankha555** [matthiaskoenig/sbmlutils#295]
Currently, any runtime errors in the Javascript in the report view causes the application to permanently break. As a result, clicking the back button does not work. This problem also persists when the report view page is refreshed and all the data is lost. This might add to bad user experience. 

Solution:
- [ ] Migrate all vuex state variables to localStorage of browser. This will make the state data persist accross page refreshements.

**Comment by matthiaskoenig** [comment]
Please keep/migrate all application data in the vuex store. We don't want to have anything in localStorage. Vuex is the correct solution to handle state data for a Vue application.
The correct solution here is to do a page forward depending on the Vuex state.
I.e. if you load the `report/` endpoint and no state exists in the vuex state (i.e. no model loaded) the page should forward to `/`.

**Comment by matthiaskoenig** [comment]
Just to add to this. The better/correct solution is here:
- the backend creates an id for a given sbml (this is like a job task and would be a hash for the SBMLDocument), calling this `job_id` here
- the frontend renders a given SBML with its hash on a corresponding url, i.e. you have to use the `report/<job_id>/` as an endpoint which uses the `Report` Component to render the data for the `job_id`
- the backend would cash the JSON data for a given `job_id` for some time
- the reload of `report/<job_id>/` would then reload the report, because it can easily get the cashed data for the job, i.e. the submitted SBML

It would be great if you could implement this solution. I.e.
- [ ] move all state to vuex, no localStorage
- [ ] implement a job id for an SBMLDocument (hash), this must based on the actual SBML content and should be the same independent of submission via URL, file or text
- [ ] cash the JSON for 1 hr for a given job_id
- [ ] render a given SBML on a route based on the job_id, i.e. `report/job_id`

**Comment by matthiaskoenig** [comment]
Updated this. The job id should be unique per SBML report request. I.e. if somebody sends a file to the backend a unique uuid is generated for the job. This will make debugging and logging also much easier.

**Comment by sankha555** [comment]
From what I understand from your suggestions Sir, I think we are looking for the following:

1. Whenever a user makes a request for a model (say BIO0001), the contents of the file along with the timestamp of the request is hashed together to create a ```job_id```.
2. The content of the model is cached and should be stored for around an hour in a temp directory (maybe we'll have to use a cron job for this)
3. next time if a user asks for the same model, we just return the stored report and no need to re-generate the report.
4. We'll be creating a layer of logging above this in the backend for logging report generation processes based on the job_id.

I hope I have got the idea to be implemented correctly till now Sir. Also, can we drop the ```job_id``` in the frontend report url because it is not required there I suppose. We will require the job id only in the backend.  

Please let me know if you have more suggestions for me on this, meanwhile I'll start creating a file in the backend to handle the first two points.

**Comment by matthiaskoenig** [comment]
Not exactly.
From what I understand from your suggestions Sir, I think we are looking for the following:

1. Whenever a user makes a request to create a report a unique id for the request is generated (using `uuid`). Based on the uuid we can store debug and logging information. 
2. The JSON content of the model is cached for the uuid for 1 hr. This is just done via a simple cache in the backend storing information for the request `d[uuid] = {'model_json': json, "timestamp": ..., `sbml`: sbml}
3. The frontend will render the report on an url endpoint corresponding to the job_id, i.e. `https://sbml4humans.de/report/<job_id>`
4. If `https://sbml4humans.de/report/<job_id>` is reloaded we request the data for the jobid. I.e. there is an endpoint in fastapi `get_json_by_uuid` which will return the cashed content or an error message if the cach is invalidated/uuid does not exist.
5. We'll be creating a layer of logging above this in the backend for logging report generation processes based on the job_id.

The job id in the frontend url is crucial ! because you want to have multiple tabs with different models. Otherwise a reload of the tab will not work and you have to make the tabs unique for the model reports! This also requires that you handle your state correctly in vuex!. I.e. there is not a single state for a report, but you have to store the report state based on the uuid!.

So no caching of the SBML in the backend!

**Comment by sankha555** [comment]
I see it now, I'll try to formulate a solution to managing the vuex state better to accomplish this.
