### ISSUE TITLE
Missing validation of units in parameters.

### ISSUE THREAD

**Issue by janekg89** [matthiaskoenig/sbmlutils#350]
I think the example below should raise a validation error as the parameter unit is not a pint unit. However, it does not. 

```python
Reaction(
        "DEXEX",
        name="DEX export",
        equation="dex -> dex_ext",
        sboTerm=SBO.TRANSPORT_REACTION,
        rules=[],
        pars=[
            # > to >> 1, scaling relative to metabolism
            Parameter(
                "DEXEX_f",
                390,
                unit="dimensionless",
                name="scaling factor DEX export relative to metabolic reactions",
            ),
        ],
        formula=(
            "DEXCYP3A4_Vmax * DEXEX_f * Vin * dex/(DEXEX_Km_dex + dex)",
            U.mmole_per_min,
        ),
```

**Comment by matthiaskoenig** [comment]
You have to add the objects to the model, otherwise no validation can be performed. 
I.e. you defined the reactions but did not assign them to the model via `_m.reactions = [ ... ]`. Only in the context of the model the units can be validated. 
I added an additional warning on object creation, but the main issue is that the objects were not added to the model.
